#!/bin/sh

PROJECT_PATH=$(dirname "$(dirname "$(readlink -f "$0")")")

cd "$PROJECT_PATH" \
&& "$PROJECT_PATH/node_modules/.bin/onchange" \
  "$PROJECT_PATH/{__tests__,src}/**/*.{js,css,scss}" \
  -- \
  "$PROJECT_PATH/node_modules/.bin/prettier-eslint" \
  --write \
  {{changed}}
