#!/bin/sh

PROJECT_PATH=$(dirname "$(dirname "$(readlink -f "$0")")")

cd "$PROJECT_PATH" \
&& "$PROJECT_PATH/node_modules/.bin/onchange" \
  "$PROJECT_PATH/{__tests__,src}/**/*.{js,jsx}" \
  -- \
  "$PROJECT_PATH/node_modules/.bin/eslint" \
  --fix \
  {{changed}}
