export default {
  FETCH_TODOS_BEGINS: 'FETCH_TODOS_BEGINS',
  FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
  FETCH_TODOS_ERROR: 'FETCH_TODOS_ERROR',
  TOGGLE_TODO: 'TOGGLE_TODO',
  CHANGE_PAGE: 'CHANGE_PAGE',
  ADD_TODO: 'ADD_TODO',
  REM_TODO: 'REM_TODO'
};
